- name: install mysql
  apt:
    name:
      - mysql-server
      - python-mysqldb
    update_cache: yes
- name: conf
  copy:
    src: mysql.conf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql
- name: User
  mysql_user:
    name: "{{wp_db_username}}"
    password: "{{wp_db_password}}"
    priv: '*.*:ALL'
    state: present
    host: "%"
- name: Create DB
  mysql_db:
    name: "{{wp_db_name}}"
    state: present
    login_user: "{{wp_db_username}}"
    login_password: "{{wp_db_password}}"

